language: rust
cache: cargo

rust:
  - stable

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rustfmt-preview

script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose
