[package]
name = "merge-mates"
version = "0.7.0"
authors = ["jeff-k <jeff_k@fastmail.com>"]

[dependencies]
bio-streams = { git="https://github.com/jeff-k/bio-streams.git" }
flate2 = "1.0"
clap = { version="^4", features=["derive"] }
